### ISSUE TITLE
Error "Cant open device /dev/ttyUSB0 

### ISSUE THREAD

**Issue by Hazuka** [BotoX/xiaomi-m365-compatible-bms#42]
all is in the title. I have the USBasp and the V1.6 BMS and i CANT find any solutions to program it.. Any help? :)

**Comment by Hazuka** [comment]
![image](https://user-images.githubusercontent.com/17553127/91587024-7bb2dc00-e956-11ea-9d49-c0282a830c60.png)


i have no com port in Device list of PlatformIO... any advice?

**Comment by Hazuka** [comment]
![image](https://user-images.githubusercontent.com/17553127/91587134-a735c680-e956-11ea-8ce6-06ade603df11.png)

But its detected by Windows. what goes wrong ? XD

**Comment by BotoX** [comment]
Upload protocol Arduino is not usbasp
It's for uploading the code via uart when using a bootloader
Usbasp is used with avrdude to upload bootloader
But it can also be used for firmware with avrdude
Or with platforming, read the documentation of platformio avr

**Comment by Hazuka** [comment]
> Upload protocol Arduino is not usbasp
> It's for uploading the code via uart when using a bootloader
> Usbasp is used with avrdude to upload bootloader
> But it can also be used for firmware with avrdude
> Or with platforming, read the documentation of platformio avr

i cant see any port.. can you explain what need to do?

**Comment by Hazuka** [comment]
Finally need to removed ENTIERELY the WinUSB drivers for it to make an exchange for libusb drivers. problem solved. Thanks you Botox for your message ;)

> Upload protocol Arduino is not usbasp
> It's for uploading the code via uart when using a bootloader
> Usbasp is used with avrdude to upload bootloader
> But it can also be used for firmware with avrdude
> Or with platforming, read the documentation of platformio avr
