### ISSUE TITLE
Recover from cut the trace (Yes I am stupic I didnt read about it ~2 years ago or this warning was not there :-))

### ISSUE THREAD

**Issue by AdamWeglarz** [BotoX/xiaomi-m365-compatible-bms#55]
Hi,

I had mine setup with cut the trace working for more than a year. Later I stopped using my scooter due to covid. Now I wanted to check everything and make it right so I have removed cut the trace from my esc and now I have problem with balancing 11th of 13 cells. It stays 1,5V below other when fully charged (4,05) and other are around 4,19.
Is there any way to fix BMS?

**Comment by BotoX** [comment]
Let the BMS sit for a few days/weeks and it should balance out, slowly because 1.5V is a loooot, that cell group might be damaged and needs to be replaced
Or if your firmware is old maybe there is bug in it, update could help.
However I'd personally connect a single cell charger to that cell group and charge it myself.
And check with a multimeter before it the BMS is measuring correctly
Post your debug_print() in any case

**Comment by AdamWeglarz** [comment]
Hi,

I am recharging this cell. And than it is ok. But after night BMS is decharching this cell even without changer on fully charged battery! This is one issue. Second issue is that when I charge battery, this cell remains at level of 4 maybe 4,05 volt and rest is around 4.2. 
I have exchanged also batteries to checked ones with good capacity (although old ones are also good).
I did update firmware succesfully, but it was latest one previosly as I already make an upgrade some time ago to fix issues with stability - BTW thanks for that :-)

I am not able to get debug. I have problem with sending commands to controler with my serial port. I am able to read BOOTED, but neither with your script neither with putty I cannot send anything. Any hint how what can be done wrong (I am able to connect only on windows using FTDI usb to serial - most reliable one I know)

**Comment by BotoX** [comment]
Unplug the BMS from the battery (big balance connector) and let it sit for a day, check if the cell is discharging.
Is the voltage reading on that cell group correct in the m365 app?

**Comment by AdamWeglarz** [comment]
OK, I have balanced manually all cells. 

Should I leave ESC connected?

Adam

**Comment by BotoX** [comment]
I thought you removed the battery from your scooter lol
ESC can stay connected, doesn't draw and power when it's off.
Take note of the cell voltages and then check again in 24 hours

**Comment by AdamWeglarz** [comment]
Hi,

After one day when BMS was connected almost 30% of battery was off and cells 9-13 were significantly more discharged.
This is why. One resistor with marking 151 and one probably transistor marked y2 were getting hot.
Do you have an idea what exactly is this Y2 element? I have written to LLT - I hope they will answer, but if not...
![252223972_202923755344598_1370933680354393965_n](https://user-images.githubusercontent.com/45738893/140590962-1ce3ef15-6f83-4119-b920-da5c0bcafc57.jpg)
a06bb954dd75.jpg)
![252938130_3057380161175408_4799415155525658234_n](https://user-images.githubusercontent.com/45738893/140590961-12204bea-b0d4-4aa5-9cfe-1a4bb9ebdb6f.jpg)
![rezystor](https://user-images.githubusercontent.com/45738893/140590889-92121fc7-41b5-4382-9df9-a005c6d3c748.jpg)
![tranzystor](https://user-images.githubusercontent.com/45738893/140591007-9b2736da-c615-41bb-83d0-20c3a88efa9f.jpg)

**Comment by BotoX** [comment]
The three legged one is a transistor that can be switched on and off by the TI BQ chip through I2C/software.
When it turns on that cell is discharged through the resistors on the other side.
That should only happen when my software detects (from the voltage readings of the TI BQ chip) that one/some cells have a higher voltage than the others.
As always, I'd recommend a debug_print() - you can see the voltages there and which cells are currently being balanced/discharged.
However if the battery is already unbalanced then obviously the BMS is going to try and balance it.
So if you suspect a hardware issue I'd suggest manually balancing those cells (to a certain degree)
and then setting the balance threshold in your config very high:
https://github.com/BotoX/xiaomi-m365-compatible-bms/blob/master/src/main.h#L71
Like to 500mV, then the software would not turn on balancing and you can check if the BMS is still discharging the cell.
Could be a faulty transistor, or faulty voltage reading which triggers balancing wrongfully, etc.

**Comment by AdamWeglarz** [comment]
I will try to replace this transistor and maybe resistor. Thats why I am looking for what it is.
I have bought second BMS and this second one is doing great job balancing battery after this faulty one.

Adam

**Comment by AdamWeglarz** [comment]
I have measured this transistor with diode test and it it short circuited between base and collector.
Based on marking and parameters I think this might this one SS8550
[ss8550_galaxy.pdf](https://github.com/BotoX/xiaomi-m365-compatible-bms/files/7499554/ss8550_galaxy.pdf)

They are available in Poland in one shop - I keep finger crossed. Resistor keeps proper parameters

**Comment by AdamWeglarz** [comment]
I was able to upload new FW
![255020033_672582437058712_7714097838147005961_n](https://user-images.githubusercontent.com/45738893/141203576-087d2281-22f1-47ad-856a-715cfaa34f4b.jpg)
First check:
![256050389_409511004153147_4507192893386431715_n](https://user-images.githubusercontent.com/45738893/141203668-2f251bc5-eeb8-41d1-a132-9e8ef913bfbd.jpg)
after one hour:
![255004168_314475076868331_3927584562362954939_n](https://user-images.githubusercontent.com/45738893/141203706-aad0b27a-2eae-46cc-a74b-bbb200083c8d.jpg)
started to charge battery:
![255091419_953604635233565_7752132918314732871_n](https://user-images.githubusercontent.com/45738893/141203923-51f4f75a-a643-4540-b902-f25bb29e407d.jpg)

It a great chance that I have fixed it successfully!

Adam

**Comment by AdamWeglarz** [comment]
Its charged fully and perfectly balanced. Tomorrow is time for drive test :-)

**Comment by AdamWeglarz** [comment]
BMS is totally working!
